// packages/solid-spacegraph/src/index.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { SpaceGraph } from 'spacegraphjs';
import type { GraphSpec, SpaceGraphOptions } from 'spacegraphjs';

export interface SpaceGraphProps {
    spec?: GraphSpec;
    url?: string;
    options?: SpaceGraphOptions;
    class?: string;
    style?: any;
    onReady?: (sg: SpaceGraph) => void;
}

export const SpaceGraphComponent = (props: SpaceGraphProps) => {
    let containerRef: HTMLDivElement | undefined;
    let sgInstance: SpaceGraph | null = null;

    onMount(() => {
        if (!containerRef) return;

        const init = async () => {
            try {
                if (props.url) {
                    sgInstance = await SpaceGraph.fromURL(props.url, containerRef!, props.options);
                } else {
                    sgInstance = new SpaceGraph(containerRef!, props.options);
                    if (props.spec) {
                        sgInstance.graph.fromJSON(props.spec);
                    }
                }
                await sgInstance.init();
                sgInstance.render();
                if (props.onReady) props.onReady(sgInstance);
            } catch (err) {
                console.error('[SolidSpaceGraph] Initialization failed', err);
            }
        };

        init();
    });

    createEffect(() => {
        if (sgInstance && props.spec && !props.url) {
            // Very naive diffing: just replace the graph. 
            // Better implementations would map Solid's reactive state to SpaceGraph's mutable state natively.
            sgInstance.graph.clear();
            sgInstance.graph.fromJSON(props.spec);
        }
    });

    onCleanup(() => {
        if (sgInstance) {
            sgInstance.dispose();
            sgInstance = null;
        }
    });

    return (
        <div
            ref={containerRef}
            class={props.class}
            style={{ width: '100%', height: '100%', ...props.style }}
        />
    );
};

export default SpaceGraphComponent;

// packages/react-spacegraph/src/index.tsx
import React, { useEffect, useRef } from 'react';
import { SpaceGraph } from 'spacegraphjs';
import type { GraphSpec, SpaceGraphOptions } from 'spacegraphjs';

export interface SpaceGraphProps {
    spec?: GraphSpec;
    url?: string;
    options?: SpaceGraphOptions;
    className?: string;
    style?: React.CSSProperties;
    onReady?: (sg: SpaceGraph) => void;
}

export const SpaceGraphComponent = ({
    spec,
    url,
    options,
    className,
    style,
    onReady,
}: SpaceGraphProps) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const sgRef = useRef<SpaceGraph | null>(null);

    useEffect(() => {
        if (!containerRef.current) return;

        let isMounted = true;

        const init = async () => {
            try {
                let sg: SpaceGraph;
                if (url) {
                    sg = await SpaceGraph.fromURL(url, containerRef.current!, options);
                } else {
                    sg = new SpaceGraph(containerRef.current!, options);
                    if (spec) sg.graph.fromJSON(spec);
                }

                await sg.init();

                if (!isMounted) {
                    sg.dispose();
                    return;
                }

                sg.render();
                sgRef.current = sg;
                if (onReady) onReady(sg);
            } catch (err) {
                console.error('[ReactSpaceGraph] Initialization failed', err);
            }
        };

        init();

        return () => {
            isMounted = false;
            if (sgRef.current) {
                sgRef.current.dispose();
                sgRef.current = null;
            }
        };
    }, [spec, url]); // Simple implementation. Advanced would diff spec.

    return (
        <div
            ref={containerRef}
            className={className}
            style={{ width: '100%', height: '100%', ...style }}
        />
    );
};

export default SpaceGraphComponent;
